src/EVPOS/affectationBundle/Entity/UO.php
<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Uo
 *
 * @ORM\Table("evpos_uo")
 * @ORM\Entity(repositoryClass="EVPOS\affectationBundle\Entity\UORepository")
 */
class UO
{
    public function __construct() {
        $this->listeUtilAcces = new ArrayCollection() ;
    }

    /**
    * @ORM\ManyToOne(targetEntity="EVPOS\affectationBundle\Entity\Application", inversedBy="listeUO")
    * @ORM\JoinColumn(name="code_appli", referencedColumnName="code_appli", nullable=false, onDelete="CASCADE")
    */
    private $appli;

    /**
     * @var string
     *
     * @ORM\Column(name="code_uo", type="string", length=12, nullable=false)
     * @ORM\Id
     */
    private $codeUo;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_uo", type="string", length=50, nullable=true)
     */
    private $nomUo;

    /**
     * @var boolean
     *
     * @ORM\Column(name="mig_moca", type="boolean", nullable=true)
     */
    private $migMoca;

    /**
     * @var boolean
     *
     * @ORM\Column(name="ancien_citrix", type="boolean", nullable=true)
     */
    private $ancienCitrix;

    /**
     * @var string
     *
     * @ORM\Column(name="avancement_moca", type="string", length=50, nullable=true)
     */
    private $avancementMoca;

    /**
     * @var string
     *
     * @ORM\Column(name="avancement_moca_detail", type="string", length=50, nullable=true)
     */
    private $avancementMocaDetail;

    /**
     * @var integer
     *
     * @ORM\Column(name="note_avancement_moca", type="integer", nullable=true)
     */
    private $noteAvancementMoca;

    /**
     * @var string
     * @ORM\Column(name="type_poste", type="string", length=255, nullable=true)
     */
    private $typePoste;

    /**
     * @ORM\OneToMany(targetEntity="EVPOS\affectationBundle\Entity\AccesUtilUo", mappedBy="uoAcces", cascade={"persist", "remove"})
     */
    private $listeAcces;

    /**
     * @ORM\ManyToMany(targetEntity="Silo", inversedBy="listeUO")
     * @ORM\JoinTable(name="evpos_uo_silo",
     *      joinColumns={@ORM\JoinColumn(name="code_uo", referencedColumnName="code_uo")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id_silo", referencedColumnName="id_silo")}
     *      )
     */
    private $listeSilo;

    /**
     * @ORM\OneToMany(targetEntity="EVPOS\affectationBundle\Entity\AccesServiceUo", mappedBy="uoAcces", cascade={"persist", "remove"})
     */
    private $listeServiceAcces;

    /**
     * @ORM\ManyToMany(targetEntity="Poste", mappedBy="listeUo", cascade={"persist", "remove"})
     */
    private $listePostes;

    /**
     * @var boolean
     *
     * @ORM\Column(name="existe_suapp", type="boolean", nullable=true)
     */
    private $existeSuapp;

    /**
     * @ORM\Column(name="nb_util", type="integer", nullable=true)
     */
    private $nbUtil;

    /**
     * Set existeSuapp
     *
     * @param boolean $existeSuapp
     * @return Service
     */
    public function setExisteSuapp($existeSuapp)
    {
        $this->existeSuapp = $existeSuapp;

        return $this;
    }

    /**
     * Get existeSuapp
     *
     * @return boolean
     */
    public function getExisteSuapp()
    {
        return $this->existeSuapp;
    }

    /**
     * Set codeUo
     *
     * @param string $codeUo
     * @return UO
     */
    public function setCodeUo($codeUo)
    {
        $this->codeUo = $codeUo;

        return $this;
    }

    /**
     * Get codeUo
     *
     * @return string
     */
    public function getCodeUo()
    {
        return $this->codeUo;
    }

    /**
     * Set nomUo
     *
     * @param string $nomUo
     * @return UO
     */
    public function setNomUo($nomUo)
    {
        $this->nomUo = $nomUo;

        return $this;
    }

    /**
     * Get nomUo
     *
     * @return string
     */
    public function getNomUo()
    {
        return $this->nomUo;
    }

    /**
     * Set appli
     *
     * @param \EVPOS\affectationBundle\Entity\Application $appli
     * @return UO
     */
    public function setAppli(\EVPOS\affectationBundle\Entity\Application $appli)
    {
        $this->appli = $appli;

        return $this;
    }

    /**
     * Get appli
     *
     * @return \EVPOS\affectationBundle\Entity\Application
     */
    public function getAppli()
    {
        return $this->appli;
    }

    /**
     * Set migMoca
     *
     * @param boolean $migMoca
     * @return UO
     */
    public function setMigMoca($migMoca)
    {
        $this->migMoca = $migMoca;

        return $this;
    }

    /**
     * Get migMoca
     *
     * @return boolean
     */
    public function getMigMoca()
    {
        return $this->migMoca;
    }

    public function getMigMocaLong()
    {
        switch ($this->migMoca) {
            case "1":
                $retour = "Oui";
                break;
            case "0":
                $retour = "Non";
                break;
            default:
                $retour = "";
        }
        return $retour;
    }

    /**
     * Set avancementMoca
     *
     * @param boolean $avancementMoca
     * @return UO
     */
    public function setAvancementMoca($avancementMoca)
    {
        $this->avancementMoca = $avancementMoca;

        return $this;
    }

    /**
     * Get avancementMoca
     *
     * @return string
     */
    public function getAvancementMoca()
    {
        return $this->avancementMoca;
    }

    /**
     * Set avancementMocaDetail
     *
     * @param boolean $avancementMocaDetail
     * @return UO
     */
    public function setAvancementMocaDetail($avancementMocaDetail)
    {
        $this->avancementMocaDetail = $avancementMocaDetail;

        return $this;
    }

    /**
     * Get avancementMocaDetail
     *
     * @return string
     */
    public function getAvancementMocaDetail()
    {
        return $this->avancementMocaDetail;
    }

    /**
     * Get avancementMocaIcon
     *
     * @return boolean
     */
    public function getAvancementMocaIcon()
    {
        switch ($this->avancementMoca) {
            case "4. En production":
                $icon = "glyphicon glyphicon-ok ok";
                break;
            case "3. Validé":
                $icon = "glyphicon glyphicon-ok ok";
                break;
            case "2. En cours":
                $icon = "glyphicon glyphicon-refresh";
                break;
            case "1. Pas initiée":
                $icon = "glyphicon glyphicon-remove ko";
                break;
            default:
                $icon = "glyphicon glyphicon-minus";
        }

        return $icon;
    }

    public function getEnCours() {
        switch ($this->avancementMoca) {
            case "4. En production":
                $enCours = true;
                break;
            case "3. Validé":
                $enCours = true;
                break;
            case "2. En cours":
                $enCours = true;
                break;
            default:
                $enCours = false;
        }
        return $enCours;
    }


    /**
     * Add listeAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesUtilUo $listeAcces
     * @return UO
     */
    public function addListeAcce(\EVPOS\affectationBundle\Entity\AccesUtilUo $listeAcces)
    {
        $this->listeAcces[] = $listeAcces;

        return $this;
    }

    /**
     * Remove listeAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesUtilUo $listeAcces
     */
    public function removeListeAcce(\EVPOS\affectationBundle\Entity\AccesUtilUo $listeAcces)
    {
        $this->listeAcces->removeElement($listeAcces);
    }

    /**
     * Get listeAcces
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeAcces()
    {
        return $this->listeAcces;
    }

    /**
     * Add listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceUo $listeServiceAcces
     * @return UO
     */
    public function addListeServiceAcce(\EVPOS\affectationBundle\Entity\AccesServiceUo $listeServiceAcces)
    {
        $this->listeServiceAcces[] = $listeServiceAcces;

        return $this;
    }

    /**
     * Remove listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceUo $listeServiceAcces
     */
    public function removeListeServiceAcce(\EVPOS\affectationBundle\Entity\AccesServiceUo $listeServiceAcces)
    {
        $this->listeServiceAcces->removeElement($listeServiceAcces);
    }

    /**
     * Retourne la liste des ensembles qui utilisent l'UO, sous la forme de texte
     */
    public function getListeEnsembleTxt() {
      $liste = [];
      foreach ($this->getListeServiceAcces() as $serviceAcces) {
        $numEnsemble = $serviceAcces->getServiceAcces()->getNumEnsemble() ;
        $liste[] = $numEnsemble;
      }

      $listeTxt = "";

      sort($liste);
      foreach (array_unique($liste) as $num) {
        $listeTxt = $listeTxt . " " . $num;
      }

      return $listeTxt;
    }

    /**
     * Get listeServiceAcces
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeServiceAcces()
    {
        return $this->listeServiceAcces;
    }

    public function getListeDirectionAcces() {
      $listeDirectionAcces = [];
      foreach ($this->listeServiceAcces as $accesService) {
        $codeDirection = (string)$accesService->getServiceAcces()->getDirection()->getCodeDirection();
        if (array_key_exists($codeDirection, $listeDirectionAcces)) {
          $listeDirectionAcces[$codeDirection] += (int)$accesService->getNbUtil();
        } else {
          $listeDirectionAcces[$codeDirection] = (int)$accesService->getNbUtil();
        }
      }
      return $listeDirectionAcces;
    }

    public function setTypePoste($type) {
        $this->typePoste = $type;
    }

    public function delTypePoste() {
      $this->typePoste = NULL;
    }

src/EVPOS/affectationBundle/Controller/ExportController.php
<?php

namespace EVPOS\affectationBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ExportController extends Controller
{
    #                               --- EXPORTS XML ---

    /**
     * Export XML des services
     */
    public function exportXmlServiceAction() {
        $listeDirection = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getDirectionsServices()
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service.xml.twig', array('listeDirection' => $listeDirection));
    }

    /**
     * Export XML des services, avec la liste des RIU
     */
    public function exportXmlServiceRiuAction() {
        $listeDirection = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getDirectionsServices()
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service_riu.xml.twig', array('listeDirection' => $listeDirection));
    }

    /**
     * Liste des applications et UO à migrer dans MOCA au format XML, pour exploitation dans Excel
     */
    public function listeAppliUoXmlAction() {
        $listeAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Application')
            ->getApplicationsFull()
        ;

        return $this->render('EVPOSaffectationBundle:Export:liste_appli.xml.twig', array('listeAppli' => $listeAppli));
    }

    /**
     * Liste de toutes les applications et UO au format XML, pour exploitation dans Excel
     */
    public function listeAppliUoAllXmlAction() {
        $listeAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Application')
            ->getApplicationsFull()
        ;

        return $this->render('EVPOSaffectationBundle:Export:liste_appli_all.xml.twig', array('listeAppli' => $listeAppli));
    }

    /**
     * Liste des applications à migrer dans MOCA au format XML, pour exploitation dans Excel
     */
    public function listeAppliXmlAction() {
        $listeAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Application')
            ->getApplicationsUo()
        ;

        return $this->render('EVPOSaffectationBundle:Export:liste_appli_only.xml.twig', array('listeAppli' => $listeAppli));
    }

    /**
     * Liste des applications de chaque service au format XML
     */
    public function listeAppliServiceXmlAction() {
        $listeDirServAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDirServAppli()
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_appli_service.xml.twig', array('listeDirServAppli' => $listeDirServAppli));
    }

    /**
     * Export des Services et utilisateurs
     */
    public function exportServiceUtilXmlAction() {
        $listeDirServiceUtil = $this->getDoctrine()->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDirServiceUtil()
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service_util.xml.twig', array('listeDirection' => $listeDirServiceUtil));
    }

    /**
     * Export des Services, utilisateurs et de leurs accès UO
     */
    public function exportServiceUtilUoXmlAction() {
        $listeDirServiceUtilAppli = $this->getDoctrine()->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDirServiceUtilAppli()
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service_util_uo.xml.twig', array('listeDirection' => $listeDirServiceUtilAppli));
    }

    /**
     * Export d'un service, avec l'ensemble de ses utilisateurs et de leurs accès UO
     */
    public function exportServiceUtilUoXmlServiceAction($codeService) {
        $listeDirServiceUtilAppli = $this->getDoctrine()->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDir1ServiceUtilAppli($codeService)
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service_util_uo.xml.twig', array('listeDirection' => $listeDirServiceUtilAppli));
    }

    /**
     * Export d'un utilisateur en export 33
     */
    public function exportServiceUtilUoXmlUtilAction($matUtil) {
        $listeDirServiceUtilAppli = $this->getDoctrine()->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDir1UtilUtilAppli($matUtil)
        ;
        return $this->render('EVPOSaffectationBundle:Export:liste_service_util_uo.xml.twig', array('listeDirection' => $listeDirServiceUtilAppli));
    }
}

src/EVPOS/affectationBundle/Resources/views/Export/export_appli_nexthink.xml.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Export applications pour Nexthink{% endblock%}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h3>Règles de définition des applications dans Nexthink</h3>
        <h4>Script XML à intégrer dans Nexthink</h4>
        <p>Sélectionner le script XML ci-dessous et l'importer dans Nexthink, dans "Categories".</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-10">
        <textarea name="" id="" cols="100" rows="50">
<?xml version="1.0" encoding="utf-16"?>
<Category SyntaxVersion="1">
  <Name>EMS - Code appli</Name>
  <Type>binary</Type>
  <Extra SyntaxVersion="1">
    <MinPrivileges>ANONYMOUS</MinPrivileges>
    <Description />
  </Extra>
  <Keywords>
    {% include "EVPOSaffectationBundle:Application:socle.xml.twig" %}
    {% for appli in listeAppli %}
    <Keyword>
      <Name>{{appli.codeAppli}}</Name>
      <Rank>{{loop.index}}</Rank>
      <Selector>
          select binary where
              binary.paths like "d:/appl/winapp32/{{appli.codeAppli}}/*"
              OR binary.paths like "d:/appl/winappl/{{appli.codeAppli}}/*"
              {% for uo in appli.listeUo %}
              OR binary.paths like "d:/appl/winapp32/{{uo.codeUo}}/*"
              OR binary.paths like "d:/appl/winappl/{{uo.codeUo}}/*"
              {% endfor %}
      </Selector>
      <AutotagRules SyntaxVersion="1" DataModelVersion="8">
        <Conditions>
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winapp32/{{appli.codeAppli}}/*"</Value>
          </ObjectCondition>
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winappl/{{appli.codeAppli}}/*"</Value>
          </ObjectCondition>

          {% for uo in appli.listeUo %}
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winapp32/{{uo.codeUo}}/*"</Value>
          </ObjectCondition>
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winappl/{{uo.codeUo}}/*"</Value>
          </ObjectCondition>
          {% endfor %}

        </Conditions>

        <LogicalExpression>1 OR 2
        {% if appli.listeUo %}
            {% for n in 0..(appli.listeUo|length-1) %}
             OR {{(n*2)+3}} OR {{(n*2)+4}}
            {% endfor %}
        {% endif %}
        </LogicalExpression>
      </AutotagRules>
    </Keyword>
    {% endfor %}
  </Keywords>
</Category>
        </textarea>
    </div>
</div>
{% endblock %}

src/EVPOS/affectationBundle/Resources/views/Export/export_uo_nexthink.xml.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Export UO pour Nexthink{% endblock%}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h3>Règles de définition des UO dans Nexthink</h3>
        <h4>Script XML à intégrer dans Nexthink</h4>
        <p>Séctionner le script XML ci-dessous et l'importer dans Nexthink, dans "Categories".</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-10">
        <textarea name="" id="" cols="100" rows="50">
<?xml version="1.0" encoding="utf-16"?>
<Category SyntaxVersion="1">
  <Name>EMS - Code UO</Name>
  <Type>binary</Type>
  <Extra SyntaxVersion="1">
    <MinPrivileges>ANONYMOUS</MinPrivileges>
    <Description />
  </Extra>
  <Keywords>
    {% include "EVPOSaffectationBundle:Application:socle.xml.twig" %}
    {% for uo in listeUo %}
    <Keyword>
      <Name>{{uo.codeUo}}</Name>
      <Rank>{{loop.index}}</Rank>
      <Selector>select binary where binary.paths like "d:/appl/winapp32/{{uo.codeUo}}/*" OR binary.paths like "d:/appl/winappl/{{uo.codeUo}}/*"</Selector>
      <AutotagRules SyntaxVersion="1" DataModelVersion="8">
        <Conditions>
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winapp32/{{uo.codeUo}}/*"</Value>
          </ObjectCondition>
          <ObjectCondition IsTemplate="false">
            <Object>binary</Object>
            <Field>paths</Field>
            <Comparer>like</Comparer>
            <Value>"d:/appl/winappl/{{uo.codeUo}}/*"</Value>
          </ObjectCondition>
        </Conditions>
        <LogicalExpression>1 OR 2</LogicalExpression>
      </AutotagRules>
    </Keyword>
    {% endfor %}
  </Keywords>
</Category>
        </textarea>
    </div>
</div>
{% endblock %}

src/EVPOS/affectationBundle/Resources/views/Export/liste_appli_all.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<listeAppli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
{% for appli in listeAppli %}
    <appli>
        <codeAppli>{{ appli.codeAppli }}</codeAppli>
        <nomAppli>{{ appli.nomAppli }}</nomAppli>
        <descAppli>{{ appli.descAppli }}</descAppli>
        <dispoMoca>{{ appli.dispoMocaLong }}</dispoMoca>
        <natAppli>{{ appli.natAppli }}</natAppli>
        {% if appli.serviceAppli %}
            <codeServiceAppli>{{ appli.serviceAppli.codeService }}</codeServiceAppli>
            <libServiceAppli>{{ appli.serviceAppli.libService }}</libServiceAppli>
        {% endif %}
        <secteur>
        {% if appli.secteur %}
          {{ appli.secteur.libSecteur }}
        {% endif %}
        </secteur>

        <cpi>
            {% if appli.cpi %}
              {{ appli.cpi.nomUtil }}
            {% endif %}
        </cpi>
        <nbUtilAppli>{{ appli.listeAcces| length }}</nbUtilAppli>
        <listeUo>
        {% for uo in appli.listeUo %}
            <uo>
                <codeUo>{{ uo.codeUO }}</codeUo>
                <nomUo>{{ uo.nomUo }}</nomUo>
                <migMoca>{{ uo.migMocaLong }}</migMoca>
                <avancementMoca>{{ uo.avancementMoca }}</avancementMoca>
                <typePoste>{{ uo.typePoste }}</typePoste>
                <ancienCitrix>{{ uo.ancienCitrixLong }}</ancienCitrix>
                <nbUtilUo>{{uo.listeAcces|length}}</nbUtilUo>
            </uo>
        {% endfor %}
        </listeUo>
    </appli>
{% endfor %}
</listeAppli>

src/EVPOS/affectationBundle/Resources/views/Export/liste_appli_only.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<listeAppli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
{% for appli in listeAppli %}
    {% if appli.listeUo %}
    <appli>
        <codeAppli>{{appli.codeAppli}}</codeAppli>
        <nomAppli>{{appli.nomAppli}}</nomAppli>
        <descAppli>{{appli.descAppli}}</descAppli>
        <dispoMoca>{{appli.dispoMocaLong}}</dispoMoca>
        <natAppli>{{appli.natAppli}}</natAppli>
        {% if appli.serviceAppli %}
            <codeServiceAppli>{{ appli.serviceAppli.codeService }}</codeServiceAppli>
            <libServiceAppli>{{ appli.serviceAppli.libService }}</libServiceAppli>
        {% endif %}
        <secteur>
        {% if appli.secteur %}
        {{ appli.secteur.libSecteur }}
        {% endif %}
        </secteur>
        <cpi>
            {% if appli.cpi %}
            {{appli.cpi.nomUtil}}
            {% endif %}
        </cpi>
        <nbUtil>{{appli.listeAcces| length}}</nbUtil>
    </appli>
    {% endif %}
{% endfor %}
</listeAppli>

src/EVPOS/affectationBundle/Resources/views/Export/liste_appli_service.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<listeDirServAppli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
{% for direction in listeDirServAppli %}
    <direction>
        <codeDirection>{{direction.codeDirection}}</codeDirection>
        <libDirection>{{direction.libDirection}}</libDirection>
            <services>
            {% for service in direction.listeServices %}
                <service>
                    <codeService>{{service.codeService}}</codeService>
                    <libService>{{service.libService}}</libService>
                    <applications>
                    {% for acces in service.listeAcces %}
                        <application>
                            <natAppli>{{ acces.appliAcces.natAppli }}</natAppli>
                            <codeAppli>{{acces.appliAcces.codeAppli}}</codeAppli>
                            <dispoMoca>{{acces.appliAcces.dispoMocaLong}}</dispoMoca>
                            <nomAppli>{{acces.appliAcces.nomAppli}}</nomAppli>
                            <secteur>
                            {% if acces.appliAcces.secteur %}
                            {{ acces.appliAcces.secteur.libSecteur }}
                            {% endif %}
                            </secteur>
                        </application>
                    {% endfor %}
                    </applications>
                </service>
            {% endfor %}
            </services>
    </direction>
{% endfor %}
</listeDirServAppli>

src/EVPOS/affectationBundle/Resources/views/Export/liste_dir_serv_poste_equip_util.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<listeDirServPosteUtil xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  {% for direction in listeDirection %}
  <direction>
    <codeDirection>{{direction.codeDirection}}</codeDirection>
    <libDirection>{{direction.libDirection}}</libDirection>
    <services>
      {% for service in direction.listeServices %}
      <service>
        <codeService>{{service.codeService}}</codeService>
        <libService>{{service.libService}}</libService>
        <numEnsemble>{{service.numEnsemble}}</numEnsemble>
        <postes>
          {% for poste in service.listePostes %}
          <poste>
            <avancementMigMoca>{{poste.avancementMigMoca}}</avancementMigMoca>
            <hostname>{{poste.hostname}}</hostname>
            <codeMateriel>{{poste.codeMateriel}}</codeMateriel>
            <categorie>{{poste.categorie}}</categorie>
            <modele>{{poste.modele}}</modele>
            <localisation>{{poste.localisation}}</localisation>
            <statut>{{poste.statut}}</statut>
            <typeUsage>{{poste.typeUsage}}</typeUsage>
            <licenceW8>{{poste.licenceW8Long}}</licenceW8>
            <typeReseau>{{poste.typeReseau}}</typeReseau>
            <master>{{poste.master}}</master>
            <utilisateurs>
              {% for util in poste.listeUtilisateurs %}
              <utilisateur>
                <matUtil>{{util.matUtil}}</matUtil>
              </utilisateur>
              {% endfor %}
            </utilisateurs>
            <equipements>
              {% for equipement in poste.listeEquipement %}
              <equipement>
                <codeMateriel>{{ equipement.codeMateriel }}</codeMateriel>
                <categorie>{{ equipement.categorie }}</categorie>
                <marque>{{ equipement.marque }}</marque>
                <modele>{{ equipement.modele }}</modele>
              </equipement>
              {% endfor %}
            </equipements>
          </poste>
          {% endfor %}
        </postes>
      </service>
      {% endfor %}
    </services>
  </direction>
  {% endfor %}
</listeDirServPosteUtil>

src/EVPOS/affectationBundle/Resources/views/Export/liste_direction.csv.twig
codeDirection;libDirection
{% for direction in listeDirection %}
{{direction.codeDirection}};{{direction.libDirection}}
{% endfor %}

src/EVPOS/affectationBundle/Resources/views/Export/liste_silo.csv.twig
nomSilo;typeSilo
{% for silo in listeSilo %}
{{ silo.nomSilo }};{{ silo.typeSilo }}
{% endfor %}

src/EVPOS/affectationBundle/Resources/views/Export/liste_util_poste.csv.twig
hostname;matUtil;niveauVIP
{% for poste in listePoste %}
{% for util in poste.listeUtilisateurs %}
{{poste.hostname}};{{util.matUtil}};{{util.niveauVIP}}
{% endfor %}
{% endfor %}

src/EVPOS/affectationBundle/Resources/views/Export/liste_utilisateur.csv.twig
matUtil;nomUtil;codeService;niveauVIP
{% for utilisateur in listeUtilisateur %}
{{utilisateur.matUtil}};{{utilisateur.nomUtil}};{{utilisateur.codeService}};{{utilisateur.niveauVIP}}
{% endfor %}