src/EVPOS/affectationBundle/Entity/Poste.php
<?php

namespace EVPOS\affectationBundle\Entity;

use EVPOS\affectationBundle\Entity\Utilisateur;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Poste
 *
 * @ORM\Table("evpos_poste")
 * @ORM\Entity(repositoryClass="EVPOS\affectationBundle\Entity\PosteRepository")
 */
class Poste
{
    public function __construct() {
        $this->listeUtilisateurs = new ArrayCollection();
        $this->listeUo = new ArrayCollection();
        $this->listeEquipementLie = new ArrayCollection();
    }

    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(name="hostname", type="string", length=10, nullable=true)
     */
    private $hostname;

    /**
     * @var integer
     *
     * @ORM\Column(name="code_materiel", type="string", length=25)
     */
    private $codeMateriel;

    /**
     * @var string
     *
     * @ORM\Column(name="categorie", type="string", length=255, nullable=true)
     */
    private $categorie;

    /**
     * @var string
     *
     * @ORM\Column(name="modele", type="string", length=255, nullable=true)
     */
    private $modele;

	/**
     * @var boolean
     *
     * @ORM\Column(name="licence_w8", type="boolean", nullable=true)
     */
    private $licenceW8;

    /**
     * @var boolean
     *
     * @ORM\Column(name="ssd", type="boolean", nullable=true)
     */
    private $ssd;

    /**
     * @var string
     *
     * @ORM\Column(name="localisation", type="string", length=255, nullable=true)
     */
    private $localisation;

    /**
     * @var string
     *
     * @ORM\Column(name="statut", type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @var string
     *
     * @ORM\Column(name="master", type="string", length=255, nullable=true)
     */
    private $master;

    /**
     * @var string
     *
     * @ORM\Column(name="type_reseau", type="string", length=255, nullable=true)
     */
    private $typeReseau;

    /**
     * @var string
     *
     * @ORM\Column(name="commentaire", type="text", nullable=true)
     */
    private $commentaire;


    /**
     * @var string
     *
     * @ORM\Column(name="type_usage", type="string", length=255, nullable=true)
     */
    private $typeUsage;

    /**
     * @var string
     *
     * @ORM\Column(name="avancement_moca", type="string", length=255, nullable=true)
     */
    private $avancementMigMoca;

    /**
    * @ORM\ManyToOne(targetEntity="Service", inversedBy="listePostes")
    * @ORM\JoinColumn(name="code_service", referencedColumnName="code_service", nullable=true)
    */
    private $service;

    /**
     * @ORM\ManyToMany(targetEntity="Utilisateur", inversedBy="listePostes", cascade={"detach"})
     * @ORM\JoinTable(name="evpos_poste_util",
     *      joinColumns={@ORM\JoinColumn(name="hostname", referencedColumnName="hostname")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="mat_util", referencedColumnName="mat_util")}
     * )
     */
    private $listeUtilisateurs;

    /**
     * @ORM\ManyToMany(targetEntity="Imprimante", inversedBy="listePostes", cascade={"detach"})
     * @ORM\JoinTable(name="evpos_poste_imprimante",
     *      joinColumns={@ORM\JoinColumn(name="hostname", referencedColumnName="hostname")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="printer_hostname", referencedColumnName="hostname")}
     * )
     */
    private $listeImprimantes;

    /**
     * @ORM\ManyToMany(targetEntity="UO", inversedBy="listePostes", cascade={"detach"})
     * @ORM\JoinTable(name="evpos_poste_uo",
     *      joinColumns={@ORM\JoinColumn(name="hostname", referencedColumnName="hostname")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="code_uo", referencedColumnName="code_uo")}
     * )
     */
    private $listeUo;

    /**
     * @ORM\OneToMany(targetEntity="Equipement", mappedBy="poste", cascade={"remove"})
     */
    private $listeEquipement;

    /**
     * @var boolean
     *
     * @ORM\Column(name="existe_gparc", type="boolean", nullable=true)
     */
    private $existeGparc;

    /**
     * Retourne l'adresse IP du Poste
     */
    public function getAdresseIp() {
      $retour = exec("host -W 1 ".$this->hostname);
      $adresse = preg_replace ("/^.* has address /", "", $retour);
      return $adresse;
    }

    public function getTypeReseauReel() {
      if (preg_match("/^192./", $this->getAdresseIp())) {
        $typeReseau = "WAN";
      } else {
        $typeReseau = "LAN";
      }
      return $typeReseau;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getCodeMateriel()
    {
        return $this->codeMateriel;
    }

    public function setCodeMateriel($codeMateriel) {
        $this->codeMateriel = $codeMateriel;
        return $this;
    }

    /**
     * Set hostname
     *
     * @param string $hostname
     * @return Poste
     */
    public function setHostname($hostname)
    {
        $this->hostname = $hostname;

        return $this;
    }

    /**
     * Get hostname
     *
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Poste
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set categorie
     *
     * @param string $categorie
     * @return Poste
     */
    public function setCategorie($categorie)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return string
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * Get categorie court (sans le préfixe)
     *
     * @return string
     */
    public function getCategorieCourt()
    {
        $tmp = preg_replace('/^Matériel\/Ordinateur\/Poste client\/UC\//', '', $this->categorie);
        return $tmp;
    }


    /**
     * Set modele
     *
     * @param string $modele
     * @return Poste
     */
    public function setModele($modele)
    {
        $this->modele = $modele;

        return $this;
    }

    /**
     * Get modele
     *
     * @return string
     */
    public function getModele()
    {
        return $this->modele;
    }

    /**
     * Set localisation
     *
     * @param string $localisation
     * @return Poste
     */
    public function setLocalisation($localisation)
    {
        $this->localisation = $localisation;

        return $this;
    }

    /**
     * Get localisation
     *
     * @return string
     */
    public function getLocalisation()
    {
        return $this->localisation;
    }

    /**
     * Set statut
     *
     * @param string $statut
     * @return Poste
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * Get statut
     *
     * @return string
     */
    public function getStatut()
    {
        return $this->statut;
    }

    public function getAvancementMigMoca() {
      return $this->avancementMigMoca;
    }

    public function setAvancementMigMoca($avancementMigMoca) {
      $this->avancementMigMoca = $avancementMigMoca;

      return $this;
    }

    /**
     * Add listeUtilisateurs
     *
     * @param \EVPOS\affectationBundle\Entity\Utilisateur $listeUtilisateurs
     * @return Poste
     */
    public function addListeUtilisateur(\EVPOS\affectationBundle\Entity\Utilisateur $listeUtilisateurs)
    {
        $this->listeUtilisateurs[] = $listeUtilisateurs;

        return $this;
    }

    /**
     * Remove listeUtilisateurs
     *
     * @param \EVPOS\affectationBundle\Entity\Utilisateur $listeUtilisateurs
     */
    public function removeListeUtilisateur(\EVPOS\affectationBundle\Entity\Utilisateur $listeUtilisateurs)
    {
        $this->listeUtilisateurs->removeElement($listeUtilisateurs);
    }

    /**
     * Get listeUtilisateurs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeUtilisateurs()
    {
        return $this->listeUtilisateurs;
    }

    /**
     * Supprime la liste des utilisateurs du poste
     */
    public function delListeUtilisateurs() {
        foreach ($this->listeUtilisateurs as $util) {
            $this->listeUtilisateurs->removeElement($util);
        }
    }


    /**
     * Add listeUo
     *
     * @param \EVPOS\affectationBundle\Entity\UO $listeUo
     * @return Poste
     */
    public function addListeUo(\EVPOS\affectationBundle\Entity\UO $listeUo)
    {
        $this->listeUo[] = $listeUo;

        return $this;
    }

    /**
     * Remove listeUo
     *
     * @param \EVPOS\affectationBundle\Entity\UO $listeUo
     */
    public function removeListeUo(\EVPOS\affectationBundle\Entity\UO $listeUo)
    {
        $this->listeUo->removeElement($listeUo);
    }

    /**
     * Get listeUo
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeUo()
    {
        return $this->listeUo;
    }

    /**
     * Supprime la liste des UO installées sur le poste
     */
    public function delListeUo() {
        foreach ($this->listeUo as $uo) {
            $this->listeUo->removeElement($uo);
        }
    }

    /**
     * Set service
     *
     * @param \EVPOS\affectationBundle\Entity\Service $service
     * @return Poste
     */
    public function setService(\EVPOS\affectationBundle\Entity\Service $service = null)
    {
        $this->service = $service;

        return $this;
    }

    /**
     * Get service
     *
     * @return \EVPOS\affectationBundle\Entity\Service
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Set commentaire
     *
     * @param string $commentaire
     * @return Poste
     */
    public function setCommentaire($commentaire)

src/EVPOS/affectationBundle/Controller/PosteController.php
<?php

namespace EVPOS\affectationBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use EVPOS\affectationBundle\Entity\Poste;


class PosteController extends Controller
{

	/**
	* Cherche un poste à partir de son hostname
	*/
	public function cherchePosteAction() {
		$request = $this->get('request');
		$poste = new Poste;

		$form = $this->createFormBuilder($poste)
		->add('hostname')
		->getForm();

		$form->handleRequest($request);

		if ($form->isValid()) {
			return $this->redirect($this->generateUrl('evpos_fichePoste', array('hostname' => strtoupper(trim($form['hostname']->getData())))));
		}
		return $this->render('EVPOSaffectationBundle:Poste:recherche_poste.html.twig', array('form' => $form->createView()));
	}

	/**
	* Affichage de la fiche d'un poste
	*/
	public function fichePosteAction($hostname) {
		$poste = $this->getDoctrine()
		->getManager()
		->getRepository('EVPOSaffectationBundle:Poste')
		->getPoste($hostname)
		;

		if ($poste === NULL) {
			$this->get('request')->getSession()->getFlashBag()->add('erreur', utf8_encode("Impossible de trouver le poste ".$hostname));
			return $this->render('EVPOSaffectationBundle:Default:index.html.twig');
		}
		else {
			return $this->render('EVPOSaffectationBundle:Poste:fiche_poste.html.twig', array('poste' => $poste));
		}
	}

	/**
	* Liste des postes connus
	*/
	public function listePosteAction(Request $request) {
		// Récupération du numéro de page courante
		$page = $request->query->get('page');

		if ($page < 1)
		$page = 1;

		$nbParPage = 1000;

		$listePoste = $this->getDoctrine()
		->getManager()
		->getRepository('EVPOSaffectationBundle:Poste')
		->getPostesPages($page, $nbParPage)
		;

		$nbPages = ceil(count($listePoste)/$nbParPage);
		if ($nbPages != 0 && $page > $nbPages) {
			throw $this->createNotFoundException("La page ".$page." n'existe pas.");
		}
		return $this->render('EVPOSaffectationBundle:Poste:liste_poste.html.twig',
		array('listePoste' => $listePoste,
		'nbPages' => $nbPages,
		'page' => $page));
	}

	/**
	 * Liste des postes à reprendre
	 */
	public function listePosteAReprendreAction() {
		$listePoste = $this->getDoctrine()
			->getManager()
			->getRepository('EVPOSaffectationBundle:Poste')
			->listePosteAReprendre()
		;

		return $this->render('EVPOSaffectationBundle:Poste:liste_poste_a_reprendre.html.twig',
			array('listePoste' => $listePoste))
		;
	}
	
	/**
	 * Liste des postes sous Windows XP
	 */
	public function listePosteXpAction() {
		$listePoste = $this->getDoctrine()
			->getManager()
			->getRepository('EVPOSaffectationBundle:Poste')
			->listePosteXp()
		;

		return $this->render('EVPOSaffectationBundle:Poste:liste_poste_xp.html.twig',
			array('listePoste' => $listePoste))
		;
	}
	
	/**
	 * Liste des postes sous Windows XP, par service
	 */
	public function listePosteXpServiceAction() {
		$listeService = $this->getDoctrine()
			->getManager()
			->getRepository('EVPOSaffectationBundle:Poste')
			->getNbPosteXpService()
		;

		return $this->render('EVPOSaffectationBundle:Poste:liste_poste_xp_service.html.twig',
			array('listeService' => $listeService))
		;
	}
}

src/EVPOS/affectationBundle/Resources/views/Poste/fiche_poste.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Poste {{poste.hostname}}{% endblock%}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2>
      Poste {{poste.hostname}}
    </h2>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{'poste.infoGAP'|trans}}</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-2">
        <h4>{{'poste.codeMateriel'|trans}}</h4>
        {{poste.codeMateriel}}
      </div>
      <div class="col-lg-3">
        <h4>{{'poste.categorie'|trans}}</h4>
        {{poste.categorie}}
      </div>
      <div class="col-lg-1">
        <h4>{{'poste.statut'|trans}}</h4>
        {{poste.statut}}
      </div>
      <div class="col-lg-1">
        <h4>{{'poste.licenceW8'|trans}}</h4>
        <span class="{{poste.licenceW8Icon}}"></span> {{ poste.licenceW8Long}}
      </div>
      <div class="col-lg-1">
        <h4>{{'poste.ssd'|trans}}</h4>
        <span class="{{poste.ssdIcon}}"></span> {{ poste.ssdLong}}
      </div>
      <div class="col-lg-1">
        <h4>{{'poste.master'|trans}}</h4>
        {{poste.master}}
      </div>
      <div class="col-lg-2">
        <h4>{{'poste.typeReseau'|trans}}</h4>
        Dans GPARC : {{poste.typeReseau}}<br>
        {{poste.adresseIp}} → {{poste.typeReseauReel}}
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2">
        <h4>{{'poste.service'|trans}}</h4>
        {% if poste.service %}
        <a href="{{ path('evpos_ficheService', { 'codeService' : poste.service.codeService }) }}" alt="{{ 'service.nom'|trans }}">
          {{poste.service.codeService}} : {{poste.service.libService}}
        </a>
        {% endif %}
      </div>
      <div class="col-lg-3">
        <h4>{{'poste.localisation'|trans}}</h4>
        {{poste.localisation}}
      </div>
      <div class="col-lg-1">
        <h4>{{'poste.typeUsage'|trans}}</h4>
        {{poste.typeUsage}}
      </div>
      <div class="col-lg-2">
        <h4>{{'poste.avancementMigMoca'|trans}}</h4>
        {{poste.avancementMigMoca}}
      </div>
      <div class="col-lg-3">
        <h4>{{'poste.commentaire'|trans}}</h4>
        {{poste.commentaire|raw}}
      </div>
    </div>
  </div>
</div>

<div class="panel panel-group panel-default" id="accordionEquipement" role="tablist" aria-multiselectable="true">
  <div class="panel-heading">
    <h3 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#accordionEquipement" href="#collapseEquipement" aria-expanded="true" aria-controls="collapseOne">
        {{'poste.equipementLie'|trans}}
        <div class="badge">{{poste.listeEquipement|length}}</div>
      </a>
    </h3>
  </div>
  <div id="collapseEquipement" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
      <div class="row">
        <table class="table table-striped table-bordered table-hover dataTable no-footer">
          <thead>
            <tr>
              <td class="row">{{ 'equipement.codeMateriel'|trans }}</td>
              <td class="row">{{ 'equipement.categorie'|trans }}</td>
              <td class="row">{{ 'equipement.marque'|trans}}</td>
              <td class="row">{{ 'equipement.modele'|trans }}</td>
            </tr>
          </thead>
          <tbody>
            {% for equipement in poste.listeEquipement %}
            <tr class="">
              <td class="gradeA odd">{{ equipement.codeMateriel }}</td>
              <td class="gradeA odd">{{ equipement.categorie }}</td>
              <td class="gradeA odd">{{ equipement.marque }}</td>
              <td class="gradeA odd">{{ equipement.modele }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      {{'poste.utilisateurs'|trans}}
      <div class="badge">{{poste.listeUtilisateurs|length}}</div>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <ul>
        {% for util in poste.listeUtilisateurs %}
        <li><a href="{{path('evpos_ficheUtil', {'matUtil': util.matUtil})}}">{{util.matUtil }}</a> : {{util.nomUtil}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

<div class="panel panel-group panel-default" id="accordionUo" role="tablist" aria-multiselectable="true">
  <div class="panel-heading">
    <h3 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#accordionUo" href="#collapseUo" aria-expanded="true" aria-controls="collapseOne">
        {{'poste.uo'|trans}}
        <div class="badge">{{poste.listeUo|length}}</div>
      </a>
    </h3>
  </div>
  <div id="collapseUo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
      <div class="row">
        <table class="table table-striped table-bordered table-hover dataTable no-footer">
          <thead>
            <tr>
              <td class="row" >{{ 'uo.code'|trans }}</td>
              <td class="row" >{{ 'uo.nom'|trans }}</td>
              <td class="row" >{{ 'uo.migMoca'|trans }}</td>
              <td class="row" >{{ 'uo.avancementMigMoca'|trans }}</td>
            </tr>
          </thead>
          <tbody>
            {% for uo in poste.listeUo %}
            <tr class="gradeA odd {% if uo.migMoca != true %}nonMoca{% endif %}">
              <td class="gradeA odd">
                <a href="{{ path('evpos_ficheUo', { 'codeUo': uo.codeUo }) }}">
                  {{ uo.codeUo }}
                </a>
              </td>
              <td class="gradeA odd">{{ uo.nomUo }}</td>
              <td class="gradeA odd">{{ uo.migMocaLong }}</td>
              <td class="gradeA odd">
                <span class="{{uo.avancementMocaIcon}}"></span>
                {{ uo.avancementMoca }}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-group panel-default" id="accordionPrinter" role="tablist" aria-multiselectable="true">
  <div class="panel-heading">
    <h3 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#accordionUo" href="#collapsePrinter" aria-expanded="true" aria-controls="collapseOne">
        {{'imprimante.liste'|trans}}
        <div class="badge">{{poste.listeImprimantes|length}}</div>
      </a>
    </h3>
  </div>
  <div id="collapsePrinter" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
      <div class="row">
        <table class="table table-striped table-bordered table-hover dataTable no-footer sortable">
          <thead>
            <tr>
              <td class="row" >{{ 'imprimante.hostname'|trans }}</td>
            </tr>
          </thead>
          <tbody>
            {% for imprimante in poste.listeImprimantes %}
            <tr class="gradeA odd">
              <td class="gradeA odd">{{ imprimante.hostname }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/EVPOS/affectationBundle/Resources/views/Poste/liste_poste.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}{{ 'poste.liste'|trans }}{% endblock%}

{% block content %}
<h4>{{ 'poste.liste'|trans }}</h4>
<table class="table table-striped table-bordered table-hover dataTable no-footer">
  <thead>
    <tr>
      <td class="row">{{ 'poste.codeMateriel'|trans }}</td>
      <td class="row">{{ 'poste.hostname'|trans }}</td>
      <td class="row">{{ 'poste.categorie'|trans }}</td>
      <td class="row">{{ 'poste.modele'|trans }}</td>
      <td class="row">{{ 'poste.ecran'|trans }}</td>
      <td class="row">{{ 'poste.statut'|trans }}</td>
      <td class="row">{{ 'poste.service'|trans }}</td>
      <td class="row">{{ 'poste.utilisateurs'|trans }}</td>
      <td class="row">{{ 'poste.uo'|trans }}</td>
      <td class="row">{{ 'poste.master'|trans }}</td>
      <td class="row">{{ 'poste.typeReseau'|trans }}</td>
      <td class="row">{{ 'poste.licenceW8'|trans }}</td>
      <td class="row">{{ 'poste.equipementLie'|trans }}</td>
      <td class="row">{{ 'poste.commentaire'|trans }}</td>
    </tr>
  </thead>
  <tbody>
    {% for poste in listePoste %}
    <tr class="gradeA odd">
      <td class="">{{ poste.codeMateriel }}</td>
      <td class=""><a href="{{path('evpos_fichePoste', {'hostname': poste.hostname})}}">{{poste.hostname }}</a></td>
      <td class="">{{ poste.categorieCourt }}</td>
      <td class="">{{ poste.modele }}</td>
      <td class="">
        {% for ecran in poste.listeEcran %}
        {{ecran}}
        {% endfor %}
      </td>
      <td class="">{{ poste.statut }}</td>
      <td class=""></td>
      <td class="">
        <ul>
          {% for util in poste.listeUtilisateurs %}
          <li>
            <a href="{{path('evpos_ficheUtil', {'matUtil': util.matUtil})}}">{{util.matUtil}}</a> : {{util.nomUtil}}
          </li>
          {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
          {% for uo in poste.listeUo %}
          <li>
            <a href="{{ path('evpos_ficheAppli', { 'codeAppli': uo.appli.codeAppli }) }}">
              {{ uo.appli.codeAppli }}
            </a>
            :
            <a href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">
              {{ uo.codeUo }}
            </a>- {{ uo.nomUo }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>{{poste.master}}</td>
        <td>{{poste.typeReseau}}</td>
        <td><span class="{{poste.licenceW8Icon}}"></span> {{ poste.licenceW8Long}}</td>
        <td>{{poste.listeEquipement|length}}</td>
        <td>{{ poste.commentaire|raw }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if nbPages > 1 %}
  <nav>
    <ul class="pagination">
      {% for p in range(1, nbPages) %}
      <li {% if p == page %}class="active"{% endif %}><a href="{{ path('evpos_listePoste', {'page': p}) }}">{{p}}</a></li>
      {% endfor %}
    </ul>
  </nav>
  {% endif %}
  {%endblock%}

src/EVPOS/affectationBundle/Resources/views/Poste/liste_poste_a_reprendre.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}{{ 'poste.liste'|trans }}{% endblock%}

{% block content %}
<h4>{{ 'poste.listeReprendre'|trans }} <div class="badge">{{ listePoste | length }}</div></h4>
<table class="table table-striped table-bordered table-hover dataTable no-footer sortable">
  <thead>
    <tr>
      <td class="row">{{ 'poste.avancementMigMoca'|trans }}</td>
      <td class="row">{{ 'poste.hostname'|trans }}</td>
      <td class="row">{{ 'poste.categorie'|trans }}</td>
      <td class="row">{{ 'poste.modele'|trans }}</td>
      <td class="row">{{ 'poste.statut'|trans }}</td>
      <td class="row">{{ 'poste.service'|trans }}</td>
      <td class="row">{{ 'poste.utilisateurs'|trans }}</td>
      <td class="row">{{ 'poste.master'|trans }}</td>
      <td class="row">{{ 'poste.typeReseau'|trans }}</td>
      <td class="row">{{ 'poste.commentaire'|trans }}</td>
    </tr>
  </thead>
  <tbody>
    {% for poste in listePoste %}
    <tr>
      <td> {{poste.avancementMigMoca}} </td>
      <td class=""><a href="{{path('evpos_fichePoste', {'hostname': poste.hostname})}}">{{poste.hostname }}</a></td>
      <td class="">{{ poste.categorie }}</td>
      <td class="">{{ poste.modele }}</td>
      <td class="">{{ poste.statut }}</td>
      <td class=""><a href="{{ path('evpos_ficheService', { 'codeService' : poste.service.codeService }) }}">{{ poste.service.codeService }}</a> : {{ poste.service.libService }}</td>
      <td class="">
          {% for util in poste.listeUtilisateurs %}
              <a href="{{ path('evpos_ficheUtil', {'matUtil' : util.matUtil }) }}">{{ util.matUtil }}</a> : {{util.nomUtil}}</li>
              <br/>
          {% endfor %}
      </td>
      <td>{{poste.master}}</td>
      <td>{{poste.typeReseau}}</td>
      <td>{{ poste.commentaire|raw }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {%endblock%}

src/EVPOS/affectationBundle/Resources/views/Poste/recherche_poste.html.twig
<center>
<form action="{{path('evpos_cherchePoste')}}" method="post" {{ form_enctype(form) }}>
   {{ form_widget(form) }}
   <input type="submit" />
</form>
</center>