src/EVPOS/affectationBundle/Entity/Application.php
<?php

namespace EVPOS\affectationBundle\Entity;

use EVPOS\affectationBundle\Entity\UO;
use EVPOS\affectationBundle\Entity\Utilisateur;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Application
 *
 * @ORM\Table("evpos_application")
 * @ORM\Entity(repositoryClass="EVPOS\affectationBundle\Entity\ApplicationRepository")
 */
class Application
{
    public function __construct() {
        $this->listeUo = new ArrayCollection() ;
        $this->listeAcces = new ArrayCollection() ;
        $this->listeServiceAcces = new ArrayCollection() ;
    }

    /**
     * @var string
     *
     * @ORM\Column(name="code_appli", type="string", length=10, nullable=false)
     * @ORM\Id
     */
    private $codeAppli;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_appli", type="string", length=50, nullable=true)
     */
    private $nomAppli;

    /**
     * @var string
     *
     * @ORM\Column(name="desc_appli", type="string", length=2000, nullable=true)
     */
    private $descAppli;

    /**
     * Service en charge de l'application
     *
     * @ORM\ManyToOne(targetEntity="EVPOS\affectationBundle\Entity\Service", inversedBy="listeAppliService" )
     * @ORM\JoinColumn(name="service_appli", referencedColumnName="code_service")
     */
    private $serviceAppli;

    /**
     * @var boolean
     *
     * @ORM\Column(name="dispo_moca", type="boolean", nullable=true)
     */
    private $dispoMoca;

    /**
     * @var string
     *
     * @ORM\Column(name="nat_appli", type="string", length=2, nullable=true)
     */
    private $natAppli;

    /**
     * CPI de l'application (premier CPI récupéré de SUAPP)
     * Attention: si l'application comporte plusieurs CPI actifs, seul l'un d'eux est pris en compte
     *
     * @ORM\ManyToOne(targetEntity="EVPOS\affectationBundle\Entity\Utilisateur", inversedBy="listeAppliCpi" )
     * @ORM\JoinColumn(name="mat_cpi", referencedColumnName="mat_util")
     */
    private $cpi;

    /**
     * Secteur en charge de l'application
     * Attention: si l'application comporte plusieurs secteurs actifs, seul l'un d'eux est pris en compte
     * @ORM\ManyToOne(targetEntity="EVPOS\affectationBundle\Entity\Secteur", inversedBy="listeAppli" )
     * @ORM\JoinColumn(name="codeSecteur", referencedColumnName="codeSecteur")
     */
    private $secteur;

    /**
     * @var boolean
     *
     * @ORM\Column(name="existe_suapp", type="boolean", nullable=true)
     */
    private $existeSuapp;

    /**
     * @var integer
     *
     * @ORM\Column(name="note_avancement_moca", type="integer", nullable=true)
     */
    private $noteAvancementMoca;

    /**
     * @ORM\OneToMany(targetEntity="EVPOS\affectationBundle\Entity\UO", mappedBy="appli", cascade={"persist", "remove"})
     */
    private $listeUO;

    /**
     * @ORM\OneToMany(targetEntity="EVPOS\affectationBundle\Entity\AccesUtilAppli", mappedBy="appliAcces", cascade={"persist", "remove"})
     */
    private $listeAcces;

    /**
     * @ORM\OneToMany(targetEntity="EVPOS\affectationBundle\Entity\AccesServiceAppli", mappedBy="appliAcces", cascade={"persist", "remove"})
     */
    private $listeServiceAcces;

    /**
     * Retourne le nombre d'utilisateurs qui ont accès à l'application
     */
    public function getNbAcces() {
        return $this->listeAcces->count();
    }

    /**
     * Set codeAppli
     *
     * @param string $codeAppli
     * @return Application
     */
    public function setCodeAppli($codeAppli)
    {
        $this->codeAppli = $codeAppli;

        return $this;
    }

    /**
     * Get codeAppli
     *
     * @return string
     */
    public function getCodeAppli()
    {
        return $this->codeAppli;
    }

    /**
     * Set nomAppli
     *
     * @param string $nomAppli
     * @return Application
     */
    public function setNomAppli($nomAppli)
    {
        $this->nomAppli = $nomAppli;

        return $this;
    }

    /**
     * Get nomAppli
     *
     * @return string
     */
    public function getNomAppli()
    {
        return $this->nomAppli;
    }

    /**
     * Set descAppli
     *
     * @param string $descAppli
     * @return Application
     */
    public function setDescAppli($descAppli)
    {
        $this->descAppli = $descAppli;

        return $this;
    }

    /**
     * Get descAppli
     *
     * @return string
     */
    public function getDescAppli()
    {
        return $this->descAppli;
    }

    /**
     * Add listeUO
     *
     * @param \EVPOS\affectationBundle\Entity\UO $listeUO
     * @return Application
     */
    public function addListeUO(\EVPOS\affectationBundle\Entity\UO $listeUO)
    {
        $this->listeUO[] = $listeUO;

        return $this;
    }

    /**
     * Remove listeUO
     *
     * @param \EVPOS\affectationBundle\Entity\UO $listeUO
     */
    public function removeListeUO(\EVPOS\affectationBundle\Entity\UO $listeUO)
    {
        $this->listeUO->removeElement($listeUO);
    }

    /**
     * Get listeUO
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeUO()
    {
        return $this->listeUO;
    }

    /**
     * Set natAppli
     *
     * @param string $natAppli
     * @return Application
     */
    public function setNatAppli($natAppli)
    {
        $this->natAppli = $natAppli;

        return $this;
    }

    /**
     * Get natAppli
     *
     * @return string
     */
    public function getNatAppli()
    {
        return $this->natAppli;
    }

    /**
     * Retourne la version longue de la nature appli
     *
     * @return string
     */
    public function getNatAppliLong() {
        $libNat="Autre";
        switch($this->natAppli) {
            case "AS":
                $libNat = "Application service";
                break;
            case "AI":
                $libNat = "Application informatique";
                break;
            default:
                $libNat = "?";
        }
        return $libNat;
    }

    /**
     * Set dispoMoca
     *
     * @param boolean $dispoMoca
     * @return Application
     */
    public function setDispoMoca($dispoMoca)
    {
        $this->dispoMoca = $dispoMoca;

        return $this;
    }

    public function getDispoMocaLong()
    {
        switch ($this->dispoMoca) {
            case 1:
                $retour = "Oui";
                break;
            default:
                $retour = "Non";
        }
        return $retour;
    }

    /**
     * Get dispoMoca
     *
     * @return boolean
     */
    public function getDispoMoca()
    {
        return $this->dispoMoca;
    }

    /**
     * Add listeAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesUtilAppli $listeAcces
     * @return Application
     */
    public function addListeAcce(\EVPOS\affectationBundle\Entity\AccesUtilAppli $listeAcces)
    {
        $this->listeAcces[] = $listeAcces;

        return $this;
    }

    /**
     * Remove listeAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesUtilAppli $listeAcces
     */
    public function removeListeAcce(\EVPOS\affectationBundle\Entity\AccesUtilAppli $listeAcces)
    {
        $this->listeAcces->removeElement($listeAcces);
    }

    /**
     * Get listeAcces
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeAcces()
    {
        return $this->listeAcces;
    }

    /**
     * Set cpi
     *
     * @param \EVPOS\affectationBundle\Entity\Utilisateur $cpi
     * @return Application
     */
    public function setCpi(\EVPOS\affectationBundle\Entity\Utilisateur $cpi = null)
    {
        $this->cpi = $cpi;

        return $this;
    }

    /**
     * Get cpi
     *
     * @return \EVPOS\affectationBundle\Entity\Utilisateur
     */
    public function getCpi()
    {
        return $this->cpi;
    }

    /**
     * Add listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces
     * @return Application
     */
    public function addListeServiceAcces(\EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces)
    {
        $this->listeServiceAcces[] = $listeServiceAcces;

        return $this;
    }

    /**
     * Remove listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces
     */
    public function removeListeServiceAcces(\EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces)
    {
        $this->listeServiceAcces->removeElement($listeServiceAcces);
    }

    /**
     * Get listeServiceAcces
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeServiceAcces()
    {
        return $this->listeServiceAcces;
    }

    /**
     * Add listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces
     * @return Application
     */
    public function addListeServiceAcce(\EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces)
    {
        $this->listeServiceAcces[] = $listeServiceAcces;

        return $this;
    }

    /**
     * Remove listeServiceAcces
     *
     * @param \EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces
     */
    public function removeListeServiceAcce(\EVPOS\affectationBundle\Entity\AccesServiceAppli $listeServiceAcces)
    {
        $this->listeServiceAcces->removeElement($listeServiceAcces);
    }

    /**
     * Set serviceAppli
     */
    public function setServiceAppli($codeAppli) {
        $this->serviceAppli = $codeAppli;
    }

    /**
     * Get serviceAppli
     */
    public function getServiceAppli() {
        return $this->serviceAppli;
    }

    /**
     * Set existeSuapp
     *
     * @param boolean $existeSuapp
     * @return Application
     */
    public function setExisteSuapp($existeSuapp)
    {
        $this->existeSuapp = $existeSuapp;

        return $this;
    }

    /**
     * Get existeSuapp
     *

src/EVPOS/affectationBundle/Controller/ApplicationController.php
<?php
namespace EVPOS\affectationBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use EVPOS\affectationBundle\Entity\Application;
use EVPOS\affectationBundle\Entity\UO;

class ApplicationController extends Controller
{
    /**
     * Cherche une application
     */
    public function chercheAppliAction() {
        $request = $this->get('request');
        $appli = new Application;

        $form = $this->createFormBuilder($appli)
            ->add('codeAppli')
            ->getForm();

        $form->handleRequest($request);

        if ($form->isValid()) {
            return $this->redirect($this->generateUrl('evpos_ficheAppli', array('codeAppli' => strtoupper(trim($form['codeAppli']->getData())))));
        }
        return $this->render('EVPOSaffectationBundle:Application:recherche_appli.html.twig', array('form' => $form->createView()));
    }

    /**
     * Cherche une UO
     */
    public function chercheUoAction() {
        $request = $this->get('request');
        $uo = new UO;

        $form = $this->createFormBuilder($uo)
            ->add('codeUo')
            ->getForm();

        $form->handleRequest($request);

        if ($form->isValid()) {
            return $this->redirect($this->generateUrl('evpos_ficheUo', array('codeUo' => strtoupper(trim($form['codeUo']->getData())))));
        }
        return $this->render('EVPOSaffectationBundle:Application:recherche_uo.html.twig', array('form' => $form->createView()));
    }

    /**
     * Liste des applications et UO dans un tableau HTML
     */
    public function listeAppliAction() {
        $listeAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Application')
            ->getApplicationsUo()
        ;

        return $this->render('EVPOSaffectationBundle:Application:liste_appli.html.twig', array('listeAppli' => $listeAppli));
    }

    /**
     * Affichage de la fiche d'une UO dont le code est passé en paramètre
     */
    public function ficheUoAction($codeUo) {
        $uo = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:UO')
            ->getUoFull($codeUo)
        ;

        if ($uo == NULL) {
            $this->get('request')->getSession()->getFlashBag()->add('erreur', utf8_encode("Impossible de trouver l'UO ".$codeUo));
            return $this->render('EVPOSaffectationBundle:Default:index.html.twig');
        }
        else {
            return $this->render('EVPOSaffectationBundle:Application:fiche_uo.html.twig', array('uo' => $uo));
        }
    }

    /**
     * Affichage de la fiche d'une application dont le code est passé en paramètre
     */
    public function ficheAppliAction($codeAppli) {
        $appli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Application')
            ->getApplicationFull($codeAppli)
        ;

        if ($appli == NULL) {
            $this->get('request')->getSession()->getFlashBag()->add('erreur', utf8_encode("Impossible de trouver l'application ".$codeAppli));
            return $this->render('EVPOSaffectationBundle:Default:index.html.twig');
        } else {
            return $this->render('EVPOSaffectationBundle:Application:fiche_appli.html.twig', array('appli' => $appli));
        }
    }

    /**
     * Liste des applications de chaque service
     */
    public function listeAppliServiceAction() {
        $listeDirServAppli = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getListeDirServAppli()
        ;
        return $this->render('EVPOSaffectationBundle:Application:liste_appli_service.html.twig', array('listeDirServAppli' => $listeDirServAppli));
    }

    /**
     * Liste des UO dont la FIA reste à préparer
     */
    public function listeFiaTodoAction() {
      $listeFiaTodo = $this->getDoctrine()
        ->getManager()
        ->getRepository('EVPOSaffectationBundle:UO')
        ->getListeFiaTodo()
      ;
      return $this->render('EVPOSaffectationBundle:Application:liste_fia_todo.html.twig', array('listeFiaTodo' => $listeFiaTodo));
    }

    /**
     * Liste des UO migrèes et encore disponibles dans l'ancienne ferme Citrix
     */
    public function listeUoOldCitrixAction() {
      $listeUO = $this->getDoctrine()
        ->getManager()
        ->getRepository('EVPOSaffectationBundle:UO')
        ->getListeOldCitrix()
      ;
      return $this->render('EVPOSaffectationBundle:Application:liste_appli_old_citrix.html.twig', array('listeUO' => $listeUO));
    }
}

src/EVPOS/affectationBundle/Resources/views/Application/liste_appli.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Suivi de la migration MOCA{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8">
        <h4>{{ 'applications.liste'|trans }}</h4>
    </div>
    <div class="col-lg-4">
        <a href="{{ path('evpos_listeAppliXml')}}" class="btn btn-sm btn-default">{{'applications.liste'|trans}}</a>
        <a href="{{ path('evpos_listeAppliUoXml')}}" class="btn btn-sm btn-default">{{'applications.listeAppliUo'|trans}}</a>
    </div>
</div>
<script>
function hideDone() {
  $('#tabAppli').find('tr.done').hide();
}
function showDone() {
  $('#tabAppli').find('tr.done').show();
}
</script>
<table id="tabAppli" class="table table-striped table-bordered table-hover dataTable no-footer sortable">
    <thead>
        <tr>
            <td class="row sorting_asc" rowspan="2">{{ 'application.code'|trans }}</td>
            <td class="row" rowspan="2">
              {{ 'application.nom'|trans }}
            </td>
            <td>
              {{'application.noteAvancement'|trans}}
              <br>
              <button type="button" onclick="showDone()">{{'app.all'|trans}}</button>
              <button type="button" onclick="hideDone()">{{'app.todo'|trans}}</button>
            </td>
            <td class="row" rowspan="2">{{ 'application.nature'|trans }}</td>
            <td class="row" rowspan="2">{{ 'application.service'|trans }}</td>
            <td class="row" rowspan="2">{{ 'application.listeUoMig'|trans }}</td>
             <td class="row" rowspan="2">{{ 'application.cpi'|trans }}</td>
            <td class="row" rowspan="2">{{ 'application.dispoMoca'|trans }}</td>
            <td class="row" colspan="2">{{ 'application.nbUtil'|trans }}</td>
        </tr>

    </thead>
    <tbody>
        {% for appli in listeAppli %}
        <tr class="gradeA odd
            {% if (appli.noteAvancementMoca == "100") %}
            done
            {% endif %}
        ">
            <td class=""><a href="{{ path('evpos_ficheAppli', { 'codeAppli': appli.codeAppli }) }}">{{appli.codeAppli }}</a></td>
            <td class="">
              {{appli.nomAppli }}
            </td>
            <td>
              <progress value="{{appli.noteAvancementMoca}}" max="100" title="{{appli.noteAvancementMoca}}%">
                {{appli.noteAvancementMoca}}
              </progress>
            </td>
            <td class="">{{appli.natAppliLong }}</td>
            <td class="">
                {% if appli.serviceAppli %}
                    <a href="{{ path('evpos_ficheService', { 'codeService' : appli.serviceAppli.codeService }) }}">
                    {{appli.serviceAppli.libService}}
                    </a>
                {% endif %}
            </td>
            <td>
                <ul>
                    {% for uo in appli.listeUo %}
                    <li {% if uo.migMoca != true %}class="nonMoca"{% endif %}>
                        <a title="{{uo.avancementMoca}}" href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">
                            <span class="{{uo.avancementMocaIcon}}"></span>
                            {{uo.codeUO }}
                        </a> : {{ uo.nomUo }}
                        {% if uo.enCours %}
                        <a href="{{uo.lienFia}}" title="{{'uo.openFia'|trans}}">
                            <span class="glyphicon glyphicon-file"></span>
                        </a>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                {% if appli.cpi %}
                    {{appli.cpi.nomUtil}}
                {% endif %}
            </td>
            <td>
                {% if appli.dispoMoca %}
                    <span class="ok glyphicon glyphicon-ok"></span>
                    {% else %}
                    <span class="ko glyphicon glyphicon-remove"></span>
                {% endif %}
                {{appli.dispoMocaLong}}
            </td>
            <td>{{appli.nbAcces}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{%endblock%}

src/EVPOS/affectationBundle/Resources/views/Application/liste_appli_old_citrix.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Suivi de la migration MOCA{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h4>
          {{ 'uo.listeOldCitrix'|trans }}
          <div class="badge">{{ listeUO | length }}</div>
        </h4>
    </div>
</div>

<table id="tabAppli" class="table table-striped table-bordered table-hover dataTable no-footer sortable">
    <thead>
        <tr>
            <td class="row sorting_asc">
              {{ 'application.code'|trans }}
            </td>
            <td class="row">
              {{ 'application.nom'|trans }}
            </td>
            <td class="row">
              {{ 'uo.code'|trans }}
            </td>
            <td class="row">
              {{ 'uo.nom'|trans }}
            </td>
        </tr>
    </thead>
    <tbody>
      {% for uo in listeUO %}
      <tr>
        <td>{{uo.appli.codeAppli}}</td>
        <td>{{uo.appli.nomAppli}}</td>
        <td><a href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">{{uo.codeUo}}</a></td>
        <td>{{uo.nomUo}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{%endblock%}

src/EVPOS/affectationBundle/Resources/views/Application/liste_appli_service.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Suivi de la migration MOCA{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <h4>{{'applications.listeAppliService'|trans}}</h4>
    </div>
    <div class="col-lg-6">
        <a href="{{ path('evpos_listeServiceAppliXml') }}" class="btn btn-sm btn-default" target="_blank">
          <span class="glyphicon glyphicon-export"></span>
          {{'applications.listeAppliService'|trans}}
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-11">
        <table class="table table-striped table-bordered table-hover dataTable no-footer sortable">
            <thead>
                <tr>
                    <td class="row">{{ 'direction.code'|trans }}</td>
                    <td class="row">{{ 'direction.nom'|trans }}</td>
                    <td class="row">{{ 'service.code'|trans }}</td>
                    <td class="row">{{ 'service.nom'|trans }}</td>
                    <td class="row">{{ 'service.nbAgent'|trans }}</td>
                    <td class="row">{{ 'applications.liste'|trans }}</td>
                    <td class="row">{{ 'service.noteAvancement'|trans}}</td>
                    <td class="row">{{ 'service.numEnsemble'|trans }}</td>
                </tr>
            </thead>
            <tbody>
                {% for direction in listeDirServAppli %}
                    {% for service in direction.listeServices %}
                        <tr>
                            <td>
                                <a href="{{ path('evpos_ficheDirection', { 'codeDirection' : direction.codeDirection }) }}">
                                    {{ direction.codeDirection }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ path('evpos_ficheDirection', { 'codeDirection' : direction.codeDirection }) }}">
                                {{ direction.libDirection }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ path('evpos_ficheService', { 'codeService' : service.codeService }) }}">
                                {{ service.codeService }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ path('evpos_ficheService', { 'codeService' : service.codeService }) }}">
                                {{ service.libService }}
                                </a>
                            </td>
                            <td>
                                {{ service.listeUtilisateurs|length }}
                            </td>
                            <td>
                                {% for acces in service.listeAcces %}
                                    <p>
                                        <span
                                            {% if acces.appliAcces.dispoMoca %}
                                                class="ok glyphicon glyphicon-ok"
                                            {% else %}
                                                class="ko glyphicon glyphicon-remove"
                                            {% endif %}
                                        ></span>
                                        <a href="{{ path('evpos_ficheAppli', { 'codeAppli' : acces.appliAcces.codeAppli }) }}"
                                           title="{{ acces.appliAcces.nomAppli }}"
                                        >
                                            {{ acces.appliAcces.codeAppli }}
                                        </a> - {{ acces.appliAcces.natAppli }}
                                    </p>
                                {% endfor %}
                            </td>
                            <td>
                              <progress value="{{service.noteAvancementMoca}}" max="100" title="{{service.noteAvancementMoca}}%">
                                {{service.noteAvancementMoca}}
                              </progress>
                            </td>
                            <td>{{service.numEnsemble}}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

src/EVPOS/affectationBundle/Resources/views/Application/liste_fia_todo.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}Suivi de la migration MOCA{% endblock%}

{% block content %}
<div class="row">
  <div class="col-lg-8">
    <h4>{{'uo.listeTodo'|trans}}</h4>
  </div>
  <div class="col-lg-4">

  </div>
</div>
<table id="tabAppli" class="table table-striped table-bordered table-hover dataTable no-footer sortable">
    <thead>
        <tr>
            <td class="row">{{ 'application.code'|trans }}</td>
            <td class="row">{{ 'application.nom'|trans }}</td>
            <td class="row">{{ 'application.nature'|trans }}</td>
            <td class="row">{{ 'uo.code'|trans }}</td>
            <td class="row">{{ 'uo.nom'|trans }}</td>
            <td class="row">{{ 'uo.avancementMigMoca'|trans }}</td>
            <td class="row">{{ 'uo.nbUtil'|trans}}</td>
            <td class="row">{{ 'service.numEnsemble'|trans}}</td>
            <td class="row">{{ 'uo.ancienCitrix'|trans}}</td>
        </tr>

    </thead>
    <tbody>
        {% for uo in listeFiaTodo %}
        <tr>
          <td>
            <a href="{{path('evpos_ficheAppli', {'codeAppli': uo.appli.codeAppli})}}">
              {{uo.appli.codeAppli}}
            </a>
          </td>
          <td>{{uo.appli.nomAppli}}</td>
          <td>{{uo.appli.natAppliLong}}</td>
          <td>
            <a href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">
              {{uo.codeUo}}
            </a>
          </td>
          <td>{{uo.nomUo}}</td>
          <td>{{uo.avancementMocaDetail}}
            {% if uo.enCours %}
            <a href="{{uo.lienFia}}" title="{{'uo.openFia'|trans}}">
              <span class="glyphicon glyphicon-file"></span>
            </a>
            {% endif %}
          </td>
          <td>{{uo.nbUtil}}</td>
          <td>
            {{ uo.listeEnsembleTxt }}
          </td>
          <td>
            {% if uo.ancienCitrix %}
            <span class="ok glyphicon glyphicon-ok"></span>
            {% else %}
            <span class="ko glyphicon glyphicon-remove"></span>
            {% endif %}
            {{ uo.ancienCitrixLong }}
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{%endblock%}

src/EVPOS/affectationBundle/Resources/views/Application/recherche_appli.html.twig
<center>
<form action="{{path('evpos_cherche_appli')}}" method="post" {{ form_enctype(form) }}>
   {{ form_widget(form) }}
   <input type="submit" value="🔍"/>
</form>
</center>

src/EVPOS/affectationBundle/Resources/views/Application/recherche_uo.html.twig
<center>
<form action="{{path('evpos_cherche_uo')}}" method="post" {{ form_enctype(form) }}>
   {{ form_widget(form) }}
   <input type="submit" value="🔍" />
</form>
</center>

src/EVPOS/affectationBundle/Resources/views/Application/update_avancement.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}
{{'uo.updateAvancement'|trans}}
{% endblock%}

{% block content %}
<h2>{{'uo.updateAvancement'|trans}}</h2>
<div class="well">
  <form method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <input type="submit" class="btn btn-primary" />
  </form>
</div>
{%endblock%}

src/EVPOS/affectationBundle/Resources/views/Application/update_suapp.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}{{ 'suapp.update'|trans}}{% endblock%}

{% block content %}
<h2>{{ 'suapp.update'|trans }}</h2>
{{message}}
{%endblock%}