src/EVPOS/affectationBundle/Entity/Secteur.php
<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Secteur
 *
 * @ORM\Table("evpos_secteur")
 * @ORM\Entity(repositoryClass="EVPOS\affectationBundle\Entity\SecteurRepository")
 */
class Secteur
{
    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(name="codeSecteur", type="string", length=25)
     */
    private $codeSecteur;

    /**
     * @var string
     *
     * @ORM\Column(name="libSecteur", type="string", length=255)
     */
    private $libSecteur;

    /**
     * @var integer
     *
     * @ORM\Column(name="note_avancement_moca", type="integer", nullable=true)
     */
    private $noteAvancementMoca;


    /**
     * @ORM\OneToMany(targetEntity="Application", mappedBy="secteur", cascade={"detach"})
     */
    private $listeAppli;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set codeSecteur
     *
     * @param string $codeSecteur
     * @return Secteur
     */
    public function setCodeSecteur($codeSecteur)
    {
        $this->codeSecteur = $codeSecteur;

        return $this;
    }

    /**
     * Get codeSecteur
     *
     * @return string
     */
    public function getCodeSecteur()
    {
        return $this->codeSecteur;
    }

    /**
     * Set libSecteur
     *
     * @param string $libSecteur
     * @return Secteur
     */
    public function setLibSecteur($libSecteur)
    {
        $this->libSecteur = $libSecteur;

        return $this;
    }

    /**
     * Get libSecteur
     *
     * @return string
     */
    public function getLibSecteur()
    {
        return $this->libSecteur;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->listeAppli = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add listeAppli
     *
     * @param \EVPOS\affectationBundle\Entity\Application $listeAppli
     * @return Secteur
     */
    public function addListeAppli(\EVPOS\affectationBundle\Entity\Application $listeAppli)
    {
        $this->listeAppli[] = $listeAppli;

        return $this;
    }

    /**
     * Remove listeAppli
     *
     * @param \EVPOS\affectationBundle\Entity\Application $listeAppli
     */
    public function removeListeAppli(\EVPOS\affectationBundle\Entity\Application $listeAppli)
    {
        $this->listeAppli->removeElement($listeAppli);
    }

    /**
     * Get listeAppli
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getListeAppli()
    {
        return $this->listeAppli;
    }

    /**
     * Retourne la liste des applications informatiques
     *
     * @return \Doctrine\Common\Collections\Collection
     **/
    public function getListeAppliInfo() {
      $liste = [];
      foreach ($this->listeAppli as $appli) {
        if ($appli->getNatAppli() == "AI") {
          $liste[] = $appli;
        }
      }
      return $liste;
    }

    /**
     * Retourne la liste des applications informatiques
     *
     * @return \Doctrine\Common\Collections\Collection
     **/
    public function getListeAppliService() {
      $liste = [];
      foreach ($this->listeAppli as $appli) {
        if ($appli->getNatAppli() == "AS") {
          $liste[] = $appli;
        }
      }
      return $liste;
    }

    /**
     * Set noteAvancementMoca
     *
     * @param integer $noteAvancementMoca
     * @return UO
     */
    public function setNoteAvancementMoca($noteAvancementMoca)
    {
        $this->noteAvancementMoca = $noteAvancementMoca;

        return $this;
    }

    /**
     * Get noteAvancementMoca
     *
     * @return integer
     */
    public function getNoteAvancementMoca()
    {
        return $this->noteAvancementMoca;
    }


    /**
     * Calcul de la note d'avancement du secteur
     */
   public function calculeNoteAvancement() {
     // Somme des notes
     $sommeNote = 0;
     // Somme des notes pondérées par le nombre d'utilisateurs
     $sommeNotePonderee = 0;
     // Somme des nombres d'utilisateurs des UO de l'application
     $nbUtil = 0;
     // Nombre d'UO de l'application
     $nbUo = 0;
     foreach ($this->listeAppli as $appli) {
       foreach ($appli->getListeUo() as $uo) {
         if ($uo->getMigMoca() == "1") {
           $nb = $uo->getListeAcces()->count();
           $nbUtil += $nb ;
           $nbUo++;
           $sommeNotePonderee += $uo->getNoteAvancementMoca() * $nb ;
           $sommeNote += $uo->getNoteAvancementMoca() ;
         }
       }
     }
     if ($nbUo != 0) {
       if ($nbUtil == 0) {
         // On fait simplement la moyenne de la note d'avancement des applications
         $this->noteAvancementMoca = $sommeNote / $nbUo ;
       } else {
         // On fait la moyenne pondérée en fonction du nombre d'utilisateur
         // de chaque application
         $this->noteAvancementMoca = $sommeNotePonderee / $nbUtil;
       }
     } else {
       $this->noteAvancementMoca = NULL;
     }
   }

}

src/EVPOS/affectationBundle/Entity/UORepository.php
<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* UORepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class UORepository extends EntityRepository
{
  /**
   * Retourne la requête de sélection des codes UO
   */
  public function getListeCodeUo() {
    $qb = $this->createQueryBuilder('uo')
          ->where("uo.migMoca = true")
          ->orderBy("uo.codeUo");

    return $qb;
  }

  /**
  * Récupération de la liste des UO
  */
  public function getListeUo() {
    $query = $this->createQueryBuilder('uo')
      ->orderBy('uo.codeUo')
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
  * Récupération d'une UO à partir de son code
  */
  public function getUo($codeUo) {
    $query = $this->createQueryBuilder('uo')
      ->setParameter('code', $codeUo)
      ->where('uo.codeUo = :code')
      ->getQuery()
    ;

    return $query->getOneOrNullResult();
  }

  /**
   * Retourne la liste des UO sans FIA
   */
  public function getSansFIA() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.appli', 'appli')
      ->addSelect('appli')
      ->leftJoin('uo.listeServiceAcces', 'acces')
      ->addSelect('acces')
      ->leftJoin('appli.cpi', 'cpi')
      ->addSelect('cpi')
      ->where("uo.avancementMoca = '1. Pas initiée' and uo.migMoca = true")
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
   * Retourne la liste des UO sans utilisateurs
   */
  public function getSansUtil() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.appli', 'appli')
      ->addSelect('appli')
      ->leftJoin('appli.cpi', 'cpi')
      ->addSelect('cpi')
      ->where("uo.nbUtil = 0  and uo.migMoca = true")
      ->getQuery()
    ;

    return $query->getResult();
  }


  /**
  * Récupération d'une UO et de toutes ses informations à partir de son code
  */
  public function getUoFull($codeUo) {
    $query = $this->createQueryBuilder('uo')
      ->setParameter('code', $codeUo)
      ->leftJoin('uo.listeAcces', 'a')
      ->addSelect('a')
      ->leftJoin('a.utilAcces', 'ua')
      ->addSelect('ua')
      ->leftJoin('ua.serviceUtil', 's')
      ->addSelect('s')
      ->leftJoin('s.direction', 'd')
      ->addSelect('d')
      ->where('uo.codeUo = :code')
      ->orderBy('d.codeDirection, s.codeService, ua.nomUtil')
      ->getQuery()
    ;

    return $query->getOneOrNullResult();
  }

  /**
  * Récupération de la liste des UO qui n'existent pas dans SUAPP
  **/
  public function getUoSupprimees() {
    $query = $this->createQueryBuilder('uo')
      ->where('uo.existeSuapp = FALSE')
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
   * Liste des UO migrées sous MOCA et disponibles dans l'ancienne ferme Citrix
   */
  public function getListeOldCitrix() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.appli', 'appli')
      ->addSelect('appli')
      ->where('uo.ancienCitrix = TRUE and uo.noteAvancementMoca = 100')
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
   * Nombre d'UO dans la file d'attente d'intégration
   */
  public function getNbPipeUo($natAppli) {
    $nbUo = $this->createQueryBuilder('u')
      ->leftJoin('u.appli', 'a')
      ->select('count(u.codeUo)')
      ->setParameter('nat', $natAppli)
      ->setParameter('avct', '03. Intégration planifiée')
      ->where("a.natAppli = :nat and u.avancementMocaDetail = :avct")
      ->getQuery()
      ->getSingleScalarResult()
    ;
    return $nbUo;
  }

  /**
   * Retourne la liste des UO avec leur affectation dans les silos de prod
   */
  public function getUoSilo() {
    $query = $this->createQueryBuilder('uo')
      ->select('uo')
      ->where('uo.migMoca = true')
      ->orderBy('uo.codeUo')
      ->getQuery()
    ;

    /* Création d'un tableau d'affectation UO/silo */
    $tabUoSilo = [];

    foreach ($query->getResult() as $uo) {
      $listeSilo = [];
      $compteur = 0;
      foreach ($uo->getListeSilo() as $silo) {
        if (strpos(strtoupper($silo->getNomSilo()), 'PROD') !== false and $compteur == 0) {
          $listeSilo[] = $silo->getNomSilo();
          $compteur++;
        }
      }
      $tabUoSilo[$uo->getCodeUo()] = array("nbUtil"=>$uo->getNbUtil(), "Silo"=>$listeSilo);
      unset($listeSilo);
    }
    return $tabUoSilo;
  }

  /**
   * Retourne le tableau de répartition des utilisateurs d'UO dans les directions
   */
  public function getUoDirection() {
    $query = $this->createQueryBuilder('uo')
      ->select('uo')
      ->where('uo.migMoca = true')
      ->orderBy('uo.codeUo')
      ->getQuery()
    ;

    $tabUoDir = [];

    foreach ($query->getResult() as $uo) {
      foreach ($uo->getListeDirectionAcces() as $dir => $nb) {
          $tabUoDir[$uo->getCodeUo()][$dir] = $nb;
      }
    }

    return $tabUoDir;
  }

  /**
   * Retourne la liste des UO hébergées dans plusieurs silos de PROD
   */
  public function getUoPlusieursSilos() {
    $listeUoKo = [];
    $query = $this->createQueryBuilder('uo')
      ->select('uo.codeUo, silo.nomSilo')
      ->leftJoin('uo.listeSilo', 'silo')
      ->where("uo.migMoca = true and silo.nomSilo like '%Prod%'")
      ->orderBy('uo.codeUo')
      ->getQuery()
    ;
    return $query->getResult();
  }

  /**
  * Teste si l'UO dont le code est passé en parametre existe
  */
  public function isUo($codeUo) {
    $nbUo = $this->createQueryBuilder('u')
      ->select('count(u.codeUo)')
      ->setParameter('code', $codeUo)
      ->where('u.codeUo = :code')
      ->getQuery()
      ->getSingleScalarResult()
    ;

    if ($nbUo >= 1)
      $retour = true;
    else
      $retour = false;

    return $retour;
  }

  /**
   * Indicateurs d'avancement général des UO, par nature
   */
  public function getAvancementGeneral($nature) {
    $query = $this->createQueryBuilder('uo')
      ->select('uo.avancementMoca, count(uo.codeUo) nb')
      ->leftJoin('uo.appli', 'a')
      ->setParameter('nature', $nature)
      ->where("a.natAppli = :nature and uo.avancementMoca <> 'Non migré'")
      ->groupBy('uo.avancementMoca')
      ->orderBy('uo.avancementMoca', 'ASC')
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
   * Indicateurs d'avancement détaillé des UO, par nature
   */
  public function getAvancementDetail($nature) {
    $query = $this->createQueryBuilder('uo')
      ->select('uo.avancementMocaDetail, count(uo.codeUo) nb')
      ->leftJoin('uo.appli', 'a')
      ->setParameter('nature', $nature)
      ->where("a.natAppli = :nature and uo.avancementMocaDetail is not null")
      ->groupBy('uo.avancementMocaDetail')
      ->orderBy('uo.avancementMocaDetail', 'ASC')
      ->getQuery()
    ;
    return $query->getResult();
  }

  /**
   * Retourne le nombre total d'UO
   */
  public function getNbUo($nature) {
    $query = $this->createQueryBuilder('uo')
      ->select('count(uo.codeUo) nb')
      ->leftJoin('uo.appli', 'a')
      ->setParameter('nature', $nature)
      ->where("a.natAppli = :nature and uo.avancementMoca <> 'Non migré'")
      ->getQuery()
    ;
    return $query->getOneOrNullResult();
  }

  /**
   * Liste des UO sans aucun utilisateur
   */
  public function getSansUtilisateur() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.appli', 'a')
      ->leftJoin('a.cpi', 'cpi')
      ->select('a.codeAppli, uo.codeUo, uo.nbUtil, cpi.matUtil, cpi.nomUtil')
      ->where('uo.nbUtil = 0')
      ->getQuery()
    ;
    return $query->getResult();
  }

  /**
   * Liste des UO planifiées
   */
  public function getPlanifUo() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.listeServiceAcces', 's')
      ->addSelect('s')
      ->leftJoin('s.serviceAcces', 'sa')
      ->addSelect('sa')
      ->leftJoin('uo.appli', 'a')
      ->addSelect('a')
      ->where("sa.numEnsemble is not null and uo.noteAvancementMoca <> '100' and uo.migMoca = true")
      ->orderBy('uo.codeUo, sa.numEnsemble')
      ->getQuery();
    return $query->getResult();
  }

  /**
   * Liste des UO dont la FIA reste à préparer
   *
   * Etats :
   * - 01. FIA en cours de rédaction
   * - Pas initiée
   */
  public function getListeFiaTodo() {
    $query = $this->createQueryBuilder('uo')
      ->leftJoin('uo.appli', 'a')
      ->addSelect('a')
      ->where("uo.avancementMocaDetail in ('Pas initiée', '01. FIA en cours de rédaction') and uo.migMoca = true and uo.avancementMoca != '4. En production'")
      ->orderBy('a.codeAppli, uo.codeUo')
      ->getQuery();

    return $query->getResult();
  }

}

src/EVPOS/affectationBundle/Controller/OrganigrammeController.php
<?php

namespace EVPOS\affectationBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class OrganigrammeController extends Controller
{
    // TreeView des services et direction, en fonction du nombre d'agents
    public function treeViewOrgaAction() {
      $em = $this->getDoctrine()->getManager();

      $listeDirection = $em->getRepository('EVPOSaffectationBundle:Direction')->getDirections();
      $listeService = $em->getRepository('EVPOSaffectationBundle:Service')->getServicesActifs();
      return $this->render('EVPOSaffectationBundle:Organigramme:treeview_service.html.twig', ['listeDirection' => $listeDirection, 'listeService' => $listeService]);
    }

    // TreeView des services et direction, en fonction du nombre d'agents et de l'état de planification
    public function treeViewOrgaPlanifAction() {
      $em = $this->getDoctrine()->getManager();

      $listeDirection = $em->getRepository('EVPOSaffectationBundle:Direction')->getDirections();
      $listeService = $em->getRepository('EVPOSaffectationBundle:Service')->getServicesActifs();
      return $this->render('EVPOSaffectationBundle:Organigramme:treeview_service_planif.html.twig', ['listeDirection' => $listeDirection, 'listeService' => $listeService]);
    }

    // Liste des secteurs
    public function listeSecteurAction() {
      $listeSecteur = $this->getDoctrine()->getManager()->getRepository('EVPOSaffectationBundle:Secteur')->findAll();
      return $this->render('EVPOSaffectationBundle:Organigramme:liste_secteur.html.twig', ['listeSecteur'=>$listeSecteur]);
    }

    // Fiche secteur
    public function ficheSecteurAction($codeSecteur) {
      $secteur = $this->getDoctrine()->getManager()->getRepository('EVPOSaffectationBundle:Secteur')->getSecteur($codeSecteur);
      if ($secteur !== NULL) {
        return $this->render('EVPOSaffectationBundle:Organigramme:fiche_secteur.html.twig', ['secteur'=>$secteur]);
      } else {
        $this->get('request')->getSession()->getFlashBag()->add('erreur', utf8_encode("Impossible de trouver le secteur '".$codeSecteur."'"));
        return $this->render('EVPOSaffectationBundle:Default:index.html.twig');
      }
    }

    /**
     * Affiche la liste des directions
     */
    public function listeDirectionAction() {
        $listeDirection = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getDirectionsServices()
        ;

        return $this->render('EVPOSaffectationBundle:Utilisateur:liste_direction.html.twig', array('listeDirection' => $listeDirection));
    }

    /**
     * Affiche la fiche d'une direction dont le code est passé en paramétre
     */
    public function ficheDirectionAction($codeDirection) {
        $direction = $this->getDoctrine()
            ->getManager()
            ->getRepository('EVPOSaffectationBundle:Direction')
            ->getDirection($codeDirection)
        ;

        return $this->render('EVPOSaffectationBundle:Utilisateur:fiche_direction.html.twig', array('direction' => $direction));
    }
}

src/EVPOS/affectationBundle/Resources/views/Organigramme/fiche_secteur.html.twig
{% extends "EVPOSaffectationBundle::layout.html.twig" %}
{% block title%}
  Secteur {{secteur.codeSecteur}}
{% endblock%}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Informations générales</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
              <h4>{{'secteur.code'|trans}}</h4>
              {{secteur.codeSecteur}}
            </div>
            <div class="col-lg-4">
              <h4>{{'secteur.nom'|trans}}</h4>
              {{secteur.libSecteur}}
            </div>
            <div class="col-lg-2">
              <h4>{{'secteur.noteAvancement'|trans}}</h4>
              <progress value="{{secteur.noteAvancementMoca}}" max="100" title="{{secteur.noteAvancementMoca}}%">
                {{secteur.noteAvancementMoca}}%
              </progress>
              <br>
              {{secteur.noteAvancementMoca}}%
            </div>
        </div>
    </div>
</div>

<script>
  function showAiTodo() {
    $('#tabAI').find('tbody').find('tr').show();
    $('#tabAI').find('tr.done').hide();
  }
  function showAiAll() {
    $('#tabAI').find('tbody').find('tr').show();
    $('#tabAI').find('tr').show();
  }
  function showAiOk() {
    $('#tabAI').find('tbody').find('tr').hide();
    $('#tabAI').find('tr.done').show();
  }
</script>

<div class="panel panel-group panel-default" id="accordionAI" role="tablist" aria-multiselectable="true">
    <div class="panel-heading">
        <a role="button" data-toggle="collapse" data-parent="#accordionAI" href="#collapseAI" aria-expanded="true" aria-controls="collapseOne">
          <h3 class="panel-title">{{'secteur.listeAppliInfo'|trans}} <div class="badge">{{secteur.listeAppliInfo|length}}</div></h3>
        </a>
    </div>
    <div id="collapseAI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
        <table id="tabAI" class="table table-striped table-bordered table-hover dataTable no-footerv sortable">
            <thead>
              <tr>
                <td class="row">{{'application.code'|trans}}</td>
                <td class="row">{{'application.nom'|trans}}</td>
                <td class="row">{{'application.nature'|trans}}</td>
                <td class="row">{{'application.nbUtil'|trans}}</td>
                <td class="row">
                  {{'application.noteAvancement'|trans}}
                  <br>
                  <button type="button" onclick="showAiAll()" title="{{'app.all'|trans}}">
                    {{'app.all'|trans}}
                  </button>
                  <button type="button" onclick="showAiTodo()" title="{{'app.todo'|trans}}">
                    <span class="glyphicon glyphicon-refresh"></span>
                  </button>
                  <button type="button" onclick="showAiOk()" title="{{'app.ok'|trans}}">
                    <span class="glyphicon glyphicon-ok"></span>
                  </button>
                </td>
                <td class="row">{{'application.listeUo'|trans}}</td>
              </tr>
            </thead>
            <tbody>
              {% for appli in secteur.listeAppliInfo | sort %}
              <tr class="{% if appli.noteAvancementMoca == 100 or appli.noteAvancementMoca == null%}done{%endif%}">
                  <td class="gradeA odd">
                      <a href="{{ path('evpos_ficheAppli', { 'codeAppli': appli.codeAppli }) }}">
                      {{appli.codeAppli}}
                      </a>
                  </td>
                  <td class="gradeA odd">{{appli.nomAppli}}</td>
                  <td class="gradeA odd">{{appli.natAppli}}</td>
                  <td class="gradeA odd">{{appli.listeAcces | length}}</td>
                  <td class="gradeA odd">
                    <progress max="100" value="{{appli.noteAvancementMoca}}" title="{{appli.noteAvancementMoca}}%">
                      {{appli.noteAvancementMoca}}%
                    </progress>
                  </td>
                  <td class="gradeA odd">
                    <table>
                      {% for uo in appli.listeUo%}
                        <tr class="{% if uo.migMoca != true %}nonMoca{% endif %}">
                          <td>
                            <span class="{{uo.avancementMocaIcon}}"></span>
                          </td>
                          <td>
                            <a href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">{{uo.codeUO }}</a>
                          </td>
                          <td>
                            {% if uo.migMoca == true %}
                            <progress value="{{uo.noteAvancementMoca}}" max="100" title="{{uo.noteAvancementMoca}}%">
                              {{uo.noteAvancementMoca}}
                            </progress>
                            {% endif %}
                          </td>
                        </tr>
                      {% endfor %}
                    </table>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
</div>

<script>
  function showAsTodo() {
    $('#tabAS').find('tbody').find('tr').show();
    $('#tabAS').find('tr.done').hide();
  }
  function showAsAll() {
    $('#tabAS').find('tbody').find('tr').show();
    $('#tabAS').find('tr').show();
  }
  function showAsOk() {
    $('#tabAS').find('tbody').find('tr').hide();
    $('#tabAS').find('tr.done').show();
  }
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <a role="button" data-toggle="collapse" data-parent="#accordionAS" href="#collapseAS" aria-expanded="true" aria-controls="collapseOne">
          <h3 class="panel-title">{{'secteur.listeAppliService'|trans}} <div class="badge">{{secteur.listeAppliService|length}}</div></h3>
        </a>
    </div>
    <div id="collapseAS" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <table id="tabAS" class="table table-striped table-bordered table-hover dataTable no-footer">
            <thead>
              <tr>
                <td class="row">{{'application.code'|trans}}</td>
                <td class="row">{{'application.nom'|trans}}</td>
                <td class="row">{{'application.nature'|trans}}</td>
                <td class="row">
                  {{'application.noteAvancement'|trans}}
                  <br>
                  <button type="button" onclick="showAsAll()" title="{{'app.all'|trans}}">
                    {{'app.all'|trans}}
                  </button>
                  <button type="button" onclick="showAsTodo()" title="{{'app.todo'|trans}}">
                    <span class="glyphicon glyphicon-refresh"></span>
                  </button>
                  <button type="button" onclick="showAsOk()" title="{{'app.ok'|trans}}">
                    <span class="glyphicon glyphicon-ok"></span>
                  </button>
                </td>
                <td class="row">{{'application.listeUo'|trans}}</td>
              </tr>
            </thead>
            <tbody>
              {% for appli in secteur.listeAppliService | sort %}
              <tr class="{% if (appli.noteAvancementMoca == 100 or appli.noteAvancementMoca == null )%}
                          done
                         {%endif%}">
                  <td class="gradeA odd">
                      <a href="{{ path('evpos_ficheAppli', { 'codeAppli': appli.codeAppli }) }}">
                      {{appli.codeAppli}}
                      </a>
                  </td>
                  <td class="gradeA odd">{{appli.nomAppli}}</td>
                  <td class="gradeA odd">{{appli.natAppli}}</td>
                  <td class="gradeA odd">
                    <progress max="100" value="{{appli.noteAvancementMoca}}" title="{{appli.noteAvancementMoca}}%">
                      {{appli.noteAvancementMoca}}%
                    </progress>
                  </td>
                  <td class="gradeA odd">
                    <table>
                    {% for uo in appli.listeUo%}
                      <tr class="{% if uo.migMoca != true %}nonMoca{% endif %}">
                        <td>
                          <span class="{{uo.avancementMocaIcon}}"></span>
                        </td>
                        <td>
                          <a href="{{path('evpos_ficheUo', {'codeUo': uo.codeUo})}}">{{uo.codeUO }}</a>
                        </td>
                        <td>
                          {% if uo.migMoca == true %}
                          <progress value="{{uo.noteAvancementMoca}}" max="100" title="{{uo.noteAvancementMoca}}%">
                            {{uo.noteAvancementMoca}}
                          </progress>
                          {% endif %}
                        </td>
                      </tr>
                    {% endfor %}
                    </table>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
</div>
{% endblock %}